package com.mrex.mrexapi.utils;

public interface ResponseCodes {
    String SUCCESS_STATUS = "SUCCESS";
    String FAIL_STATUS = "FAILED";
    String USER_NOT_FOUND = "USER_NOT_FOUND";
    String USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS";
    String PASSWORD_NOT_MATCH = "PASSWORD_NOT_MATCH";
    String THIRD_PARTY_ERROR = "THIRD_PARTY_ERROR";
    String INVALID_REQUEST = "INVALID_REQUEST";
    String USERNAME_OR_PASSWORD_INVALID = "USERNAME_OR_PASSWORD_INVALID";
    String USERNAME_ALREADY_EXISTS = "USERNAME_ALREADY_EXISTS";
    String SYSTEM_ERROR = "SYSTEM_ERROR";

}
